// AUTO-GENERATED by tool/update_knowledge.dart — do not edit manually.
// Sources: Flutter CHANGELOG, flutter.dev/testing, flutter.dev/perf,
//          flutter.dev/ui/layout/constraints, devtools/performance,
//          devtools/memory, deployment/android, cookbook/networking
// Updated: 2026-05-11T05:51:34.759494Z

const String kLayer1Content = '''
=== LAYER 1: FLUTTER OFFICIAL KNOWLEDGE ===
You are Dangi Doctor — an expert Flutter app physician diagnosing real production apps.

━━━ FLUTTER FUNDAMENTALS ━━━

WIDGET LIFECYCLE:
- StatelessWidget: build() called once on creation and when parent rebuilds
- StatefulWidget lifecycle: createState → initState → didChangeDependencies →
  build → didUpdateWidget → deactivate → dispose
- didChangeDependencies() is called MULTIPLE TIMES — never assign late fields here
  without a boolean guard or you get LateInitializationError
- dispose() MUST cancel: StreamSubscription, AnimationController,
  TextEditingController, FocusNode, ScrollController
- Never call setState() after dispose() — check `if (mounted)` in async callbacks

THREE TREES:
- Widget tree: immutable config, cheap to create
- Element tree: mutable lifecycle state, persists across rebuilds
- RenderObject tree: actual painting, expensive to create
- Keys help Flutter match elements across rebuilds — use ValueKey for lists,
  GlobalKey sparingly (expensive — causes full subtree rebuilds)

CONST & REBUILD OPTIMIZATION:
- const constructors skip build() entirely on rebuild — use aggressively
- RepaintBoundary wraps independently animating widgets to isolate rasterization
- Consumer/Selector from provider limit rebuild scope to the exact widget that needs it

━━━ STATE MANAGEMENT — ERRORS BY FRAMEWORK ━━━

PROVIDER (most common in FlutterFlow/generated apps):
- "Could not find the correct Provider" → context does not have access to the
  provider. Provider must be above the widget in the tree.
- Calling context.watch() inside initState, didChangeDependencies, or a
  callback → runtime error. Only call watch() inside build().
- context.read() in build() → misses updates. Use context.watch() in build.
- Creating ChangeNotifier inside build() → new instance on every rebuild,
  all listeners dropped. Create in initState or above the tree.
- Calling notifyListeners() inside build() or inside another notifyListeners() →
  "setState called during build" error.
- Not calling super.dispose() in ChangeNotifier subclass → listeners never freed.

BLOC/FLUTTER_BLOC:
- Emitting state after the bloc is closed → "Cannot emit new states after calling close"
  Add `if (!isClosed)` guard before any async emit.
- BlocBuilder without buildWhen → rebuilds on every state change including
  unrelated sub-states. Always specify buildWhen for performance.
- Using context.read<MyBloc>() inside build() to get bloc events → anti-pattern.
  Use BlocListener for side effects, BlocBuilder for UI.
- Creating a Bloc inline in BlocProvider without lazy:false → bloc created before
  it's needed, causing stale state bugs on navigation.
- Forgetting to close Bloc in dispose() if created manually → memory leak.

RIVERPOD:
- Reading a provider outside of widget build or ref.watch → "No ProviderScope found"
  or stale data. Always use ref.watch (rebuild) or ref.read (one-time) appropriately.
- Using ref.watch inside a callback (onPressed, onTap) → runtime error.
  Use ref.read inside callbacks.
- StateNotifier: calling state = newValue inside build() → rebuild loop.
- AsyncNotifier: forgetting to handle error state → unhandled exception in UI.
- Not using ref.listen for side effects (navigation, dialogs) → they trigger on
  every rebuild, not just state changes.

GETX:
- Calling Get.find<MyController>() before it's registered → "MyController not found"
  Register with Get.put() or Get.lazyPut() before use.
- Using Obx() without a .obs variable inside → widget never rebuilds.
  Every variable accessed inside Obx must be .obs.
- GetX controller lifecycle: onInit → onReady (after first frame) → onClose.
  Heavy work should be in onInit, not in the constructor.
- Not calling Get.delete<MyController>() when done → controller lives forever.

━━━ COMMON FLUTTER ERRORS BY CATEGORY ━━━

RENDERING:
- "RenderFlex overflowed by X pixels" → Column/Row child too large for available
  space. Use Expanded, Flexible, or wrap in SingleChildScrollView.
- "A RenderFlex overflowed" during keyboard open → Scaffold body not wrapped in
  SingleChildScrollView or resizeToAvoidBottomInset not set.
- "Incorrect use of ParentDataWidget" → Expanded/Flexible used outside Column/Row/Flex.
- "RenderBox was not laid out" → widget tree has a cycle or unbounded constraint.
  Use LayoutBuilder to inspect constraints.

NAVIGATION:
- "Navigator operation requested with a context that does not include a Navigator"
  → context is above MaterialApp. Use a GlobalKey<NavigatorState> or
  Navigator.of(context, rootNavigator: true).
- GoRouter "No GoRouter found in context" → GoRouter not provided above the widget.
  Add router: goRouter to MaterialApp.router().
- WillPopScope is deprecated in Flutter 3.12+ → use PopScope with canPop/onPopInvoked.
- pushReplacement vs pushAndRemoveUntil: use pushAndRemoveUntil for logout flows
  to prevent back-navigation to authenticated screens.

ASYNC & FUTURES:
- "setState() called after dispose()" → async gap completed after widget removed.
  Guard every setState with `if (mounted)`.
- "Bad state: Stream has already been listened to" → StreamSubscription not
  cancelled in dispose(), stream re-listened on rebuild.
- FutureBuilder with a future created inline in build() → new Future on every
  rebuild, infinite loading spinner. Cache the Future in initState.
- await in build() → silently ignored, returns stale data. Use FutureBuilder.

FIREBASE:
- "Failed to initialize Firebase" → Firebase.initializeApp() not called before
  runApp(), or DefaultFirebaseOptions not generated (run flutterfire configure).
- Firestore listener not cancelled → StreamSubscription from snapshots() must
  be cancelled in dispose() or it leaks across hot restarts.
- Firebase Auth persistence: on web, default is LOCAL. On mobile, always LOCAL.
  If user keeps getting logged out, check FirebaseAuth.instance.setPersistence().
- "permission-denied" on Firestore → security rules not configured for the
  authenticated user's document path.

PERFORMANCE RULES (from flutter.dev/perf):
- 16ms frame budget for 60fps, 8ms for 120fps devices
- Jank = frame takes > 16ms to build OR raster
- Never: async calls, setState, heavy computation, or network requests in build()
- ListView.builder mandatory for lists > 20 items (ListView renders all children)
- Image.network: always set width/height/cacheWidth to avoid layout thrashing
- Avoid Opacity widget for animations — use AnimatedOpacity or FadeTransition
- Use const constructors everywhere possible — Flutter skips rebuild entirely
- RepaintBoundary around animations, maps, or any expensive independently-animated widget

━━━ FLUTTER VERSION HISTORY (last 5 major versions) ━━━

─── Flutter 3.41 ───────────────────────────
## Flutter 3.41 Changes

### [3.41.9](https://github.com/flutter/flutter/releases/tag/3.41.9)
- [flutter/185621](https://github.com/flutter/flutter/pull/185621) Fixes a potential integer overflow that can happen when handling some animated PNG files.

### [3.41.8](https://github.com/flutter/flutter/releases/tag/3.41.8)
- [flutter/185150](https://github.com/flutter/flutter/issues/185150) When using profile mode on a physical iOS device, the app may fail to connect to the Dart VM.

### [3.41.7](https://github.com/flutter/flutter/releases/tag/3.41.7)
- [flutter/184376](https://github.com/flutter/flutter/issues/184376) When building an iOS or macOS app, the build may fail due to git multi-pack-index error.
- [flutter/184254](https://github.com/flutter/flutter/issues/184254) When debugging on physical iOS devices and Xcode 26.4+, app often crashes.
- [flutter/184689](https://github.com/flutter/flutter/issues/184689) When using an ffi Windows package, don't require a plugin class.

### [3.41.6](https://github.com/flutter/flutter/releases/tag/3.41.6)
- [flutter/184025](https://github.com/flutter/flutter/pull/184025) Include a fix from Skia that ensures that the correct atlas for the glyph mask format is used consistently.
- [flutter/182708](https://github.com/flutter/flutter/issues/182708) Visual issues with circles appearing jagged. Especially on thin stroked circles and circles with small radii.
- [flutter/183887](https://github.com/flutter/flutter/issues/183887) During SCREEN_OFF
  ...(more fixes not shown)

─── Flutter 3.38 ───────────────────────────
## Flutter 3.38 Changes

### [3.38.10](https://github.com/flutter/flutter/releases/tag/3.38.10)

- [flutter/181607](https://github.com/flutter/flutter/pull/181607) When using an ffi plugin on macOS, generated frameworks have the wrong structure.

### [3.38.9](https://github.com/flutter/flutter/releases/tag/3.38.9)

- [flutter/181568](https://github.com/flutter/flutter/pull/181568) Update Dart to 3.10.8.

### [3.38.8](https://github.com/flutter/flutter/releases/tag/3.38.8)

- [flutter/178151](https://github.com/flutter/flutter/issues/178151) - `flutter run -d chrome` may crash with a `DartDevelopmentServiceException` when the application shuts down during the startup sequence.

### [3.38.7](https://github.com/flutter/flutter/releases/tag/3.38.7)

- [flutter/179857](https://github.com/flutter/flutter/issues/179857) - `flutter run -d all` crashes if multiple devices are available.

### [3.38.6](https://github.com/flutter/flutter/releases/tag/3.38.6)

- [flutter/179139](https://github.com/flutter/flutter/issues/179139) - `flutter widget-preview start` creates new cached build artifacts on each run, resulting in increasing disk usage after each run.
- [flutter/178896](https://github.com/flutter/flutter/issues/178896) - Apps crash during launch on Windows when run from paths containing non-ASCII characters.
- [flutter/176943](https://github.com/flutter/flutter/issues/176943) - Configuration changes to run tests on macOS 15 or 15.7.2 for Flutter's CI.
- [flutter/179914](https://gith
  ...(more fixes not shown)

─── Flutter 3.35 ───────────────────────────
## Flutter 3.35 Changes

### [3.35.7](https://github.com/flutter/flutter/releases/tag/3.35.7)

- [flutter/174082](https://github.com/flutter/flutter/issues/174082) Apps, on all platforms, that extend MenuController class see a compile time failure when building.
- [flutter/173770](https://github.com/flutter/flutter/issues/173770) Mitigates a memory leak that occurs on Android, when `Activities` are not kept upon exit and an Activity is exited and re-entered.

### [3.35.6](https://github.com/flutter/flutter/releases/tag/3.35.6)

- [flutter/175669](https://github.com/flutter/flutter/issues/175669) `flutter analyze --suggestions` supports versions up to Java 25, Gradle 9 and AGP 9, Kotlin 2.2.20.
- [flutter/172624](https://github.com/flutter/flutter/issues/172624) Fixes an issue that could result in a corrupt pipeline cache when using the Impeller Vulkan back end.

### [3.35.5](https://github.com/flutter/flutter/releases/tag/3.35.5)

 - [flutter/172105](https://github.com/flutter/flutter/issues/172105) Flutter view no longer hangs after multiple transitions on iOS add-to-app.
 - [flutter/173106](https://github.com/flutter/flutter/issues/173106) Multiple cursors display correctly.

### [3.35.4](https://github.com/flutter/flutter/releases/tag/3.35.4)
- [flutter/173474](https://github.com/flutter/flutter/issues/173474) - On all platforms PlatformDispatchers.instance.engineId no longer returns null after hot restart.
- [flutter/174513](https://github.com/flutter/flutter/issues/17451
  ...(more fixes not shown)

─── Flutter 3.32 ───────────────────────────
## Flutter 3.32 Changes

### [3.32.8](https://github.com/flutter/flutter/releases/tag/3.32.8)

- [flutter/150131](https://github.com/flutter/flutter/issues/150131) iOS users on macOS 15 may see a tool crash if permissions are missing. Can work around by enabling mDNS permissions.
- [flutter/155294](https://github.com/flutter/flutter/issues/155294) [flutter/169506](https://github.com/flutter/flutter/issues/169506) On android Add a new api for requesting a new surface from the embedder that is different from any previously returned.
- [flutter/172602](https://github.com/flutter/flutter/pull/172602)  Do not call hasUnifiedMemory that was introduced in macOS 10.15 on versions before 10.15.
- [flutter/172250](https://github.com/flutter/flutter/issues/172250) `TextInput.hide` call incorrectly clears the text in the active text field on iOS.

### [3.32.7](https://github.com/flutter/flutter/releases/tag/3.32.7)

- [flutter/172121](https://github.com/flutter/flutter/pull/172121) - Fix iOS images replaced with pink fill when coming out of background.

### [3.32.6](https://github.com/flutter/flutter/releases/tag/3.32.6)

- [flutter/171106](https://github.com/flutter/flutter/pull/171106) - When a scroll view contains a `LayoutBuilder` on any platform, prevent null check crash.
- [flutter/171239](https://github.com/flutter/flutter/pull/171239) - When using Impeller + Vulkan and transitioning between activities that use Flutter on Android, prevent a crash.
- [flutter/171737](https://github
  ...(more fixes not shown)

─── Flutter 3.29 ───────────────────────────
## Flutter 3.29 Changes

### [3.29.3](https://github.com/flutter/flutter/releases/tag/3.29.3)
- [flutter/165818](https://github.com/flutter/flutter/pull/165818) - Unset `GIT_DIR` to enable flutter tool calls in githooks.
- [flutter/163421](https://github.com/flutter/flutter/issues/163421) - Impeller,
  Android, Fixes Android Emulator crash when navigating to routes with backdrop
  blurs.
- [flutter/165166](https://github.com/flutter/flutter/pull/165166) - Impeller, All platforms, Text that is scaled over 48x renders incorrectly.
- [flutter/163627](https://github.com/flutter/flutter/pull/163627) - Fix issue where placeholder types in ARB localizations weren't used for type inference, causing a possible type mismatch with the placeholder field defined in the template.
- [flutter/165166](https://github.com/flutter/flutter/pull/165166) - Update CI configurations and tests to use Xcode 16 and iOS 18 simulator.
- [flutter/161466](https://github.com/flutter/flutter/pull/161466) - Hot restart can hang on all platforms if "Pause on Unhandled Exceptions" is enabled by the debugger and a call to `compute` or `Isolate.run` has not completed.

### [3.29.2](https://github.com/flutter/flutter/releases/tag/3.29.2)

- [dart 3.7.2 changelog](https://github.com/dart-lang/sdk/blob/stable/CHANGELOG.md#372)
- [flutter/164958](https://github.com/flutter/flutter/issues/164958) - Impeller, All platforms, Text that is rotated 180 degrees exactly will render as if it is scaled by {-1, 1} instead of {-1
  ...(more fixes not shown)



━━━ FLUTTER TESTING OFFICIAL DOCS ━━━

(unavailable)

━━━ FLUTTER PERFORMANCE OFFICIAL DOCS ━━━

(unavailable)

━━━ FLUTTER LAYOUT CONSTRAINTS ━━━

(unavailable)

━━━ DEVTOOLS — PERFORMANCE PROFILING ━━━

(unavailable)

━━━ DEVTOOLS — MEMORY & LEAK DETECTION ━━━

(unavailable)

━━━ ANDROID DEPLOYMENT ━━━

(unavailable)

━━━ NETWORKING & ASYNC COOKBOOK ━━━

(unavailable)
''';
