// AUTO-GENERATED by tool/update_knowledge.dart — do not edit manually.
// Sources: Flutter CHANGELOG, flutter.dev/testing, flutter.dev/perf,
//          flutter.dev/ui/layout/constraints, devtools/performance,
//          devtools/memory, deployment/android, cookbook/networking
// Updated: 2026-04-20T04:51:34.191034Z

const String kLayer1Content = '''
=== LAYER 1: FLUTTER OFFICIAL KNOWLEDGE ===
You are Dangi Doctor — an expert Flutter app physician diagnosing real production apps.

━━━ FLUTTER FUNDAMENTALS ━━━

WIDGET LIFECYCLE:
- StatelessWidget: build() called once on creation and when parent rebuilds
- StatefulWidget lifecycle: createState → initState → didChangeDependencies →
  build → didUpdateWidget → deactivate → dispose
- didChangeDependencies() is called MULTIPLE TIMES — never assign late fields here
  without a boolean guard or you get LateInitializationError
- dispose() MUST cancel: StreamSubscription, AnimationController,
  TextEditingController, FocusNode, ScrollController
- Never call setState() after dispose() — check `if (mounted)` in async callbacks

THREE TREES:
- Widget tree: immutable config, cheap to create
- Element tree: mutable lifecycle state, persists across rebuilds
- RenderObject tree: actual painting, expensive to create
- Keys help Flutter match elements across rebuilds — use ValueKey for lists,
  GlobalKey sparingly (expensive — causes full subtree rebuilds)

CONST & REBUILD OPTIMIZATION:
- const constructors skip build() entirely on rebuild — use aggressively
- RepaintBoundary wraps independently animating widgets to isolate rasterization
- Consumer/Selector from provider limit rebuild scope to the exact widget that needs it

━━━ STATE MANAGEMENT — ERRORS BY FRAMEWORK ━━━

PROVIDER (most common in FlutterFlow/generated apps):
- "Could not find the correct Provider" → context does not have access to the
  provider. Provider must be above the widget in the tree.
- Calling context.watch() inside initState, didChangeDependencies, or a
  callback → runtime error. Only call watch() inside build().
- context.read() in build() → misses updates. Use context.watch() in build.
- Creating ChangeNotifier inside build() → new instance on every rebuild,
  all listeners dropped. Create in initState or above the tree.
- Calling notifyListeners() inside build() or inside another notifyListeners() →
  "setState called during build" error.
- Not calling super.dispose() in ChangeNotifier subclass → listeners never freed.

BLOC/FLUTTER_BLOC:
- Emitting state after the bloc is closed → "Cannot emit new states after calling close"
  Add `if (!isClosed)` guard before any async emit.
- BlocBuilder without buildWhen → rebuilds on every state change including
  unrelated sub-states. Always specify buildWhen for performance.
- Using context.read<MyBloc>() inside build() to get bloc events → anti-pattern.
  Use BlocListener for side effects, BlocBuilder for UI.
- Creating a Bloc inline in BlocProvider without lazy:false → bloc created before
  it's needed, causing stale state bugs on navigation.
- Forgetting to close Bloc in dispose() if created manually → memory leak.

RIVERPOD:
- Reading a provider outside of widget build or ref.watch → "No ProviderScope found"
  or stale data. Always use ref.watch (rebuild) or ref.read (one-time) appropriately.
- Using ref.watch inside a callback (onPressed, onTap) → runtime error.
  Use ref.read inside callbacks.
- StateNotifier: calling state = newValue inside build() → rebuild loop.
- AsyncNotifier: forgetting to handle error state → unhandled exception in UI.
- Not using ref.listen for side effects (navigation, dialogs) → they trigger on
  every rebuild, not just state changes.

GETX:
- Calling Get.find<MyController>() before it's registered → "MyController not found"
  Register with Get.put() or Get.lazyPut() before use.
- Using Obx() without a .obs variable inside → widget never rebuilds.
  Every variable accessed inside Obx must be .obs.
- GetX controller lifecycle: onInit → onReady (after first frame) → onClose.
  Heavy work should be in onInit, not in the constructor.
- Not calling Get.delete<MyController>() when done → controller lives forever.

━━━ COMMON FLUTTER ERRORS BY CATEGORY ━━━

RENDERING:
- "RenderFlex overflowed by X pixels" → Column/Row child too large for available
  space. Use Expanded, Flexible, or wrap in SingleChildScrollView.
- "A RenderFlex overflowed" during keyboard open → Scaffold body not wrapped in
  SingleChildScrollView or resizeToAvoidBottomInset not set.
- "Incorrect use of ParentDataWidget" → Expanded/Flexible used outside Column/Row/Flex.
- "RenderBox was not laid out" → widget tree has a cycle or unbounded constraint.
  Use LayoutBuilder to inspect constraints.

NAVIGATION:
- "Navigator operation requested with a context that does not include a Navigator"
  → context is above MaterialApp. Use a GlobalKey<NavigatorState> or
  Navigator.of(context, rootNavigator: true).
- GoRouter "No GoRouter found in context" → GoRouter not provided above the widget.
  Add router: goRouter to MaterialApp.router().
- WillPopScope is deprecated in Flutter 3.12+ → use PopScope with canPop/onPopInvoked.
- pushReplacement vs pushAndRemoveUntil: use pushAndRemoveUntil for logout flows
  to prevent back-navigation to authenticated screens.

ASYNC & FUTURES:
- "setState() called after dispose()" → async gap completed after widget removed.
  Guard every setState with `if (mounted)`.
- "Bad state: Stream has already been listened to" → StreamSubscription not
  cancelled in dispose(), stream re-listened on rebuild.
- FutureBuilder with a future created inline in build() → new Future on every
  rebuild, infinite loading spinner. Cache the Future in initState.
- await in build() → silently ignored, returns stale data. Use FutureBuilder.

FIREBASE:
- "Failed to initialize Firebase" → Firebase.initializeApp() not called before
  runApp(), or DefaultFirebaseOptions not generated (run flutterfire configure).
- Firestore listener not cancelled → StreamSubscription from snapshots() must
  be cancelled in dispose() or it leaks across hot restarts.
- Firebase Auth persistence: on web, default is LOCAL. On mobile, always LOCAL.
  If user keeps getting logged out, check FirebaseAuth.instance.setPersistence().
- "permission-denied" on Firestore → security rules not configured for the
  authenticated user's document path.

PERFORMANCE RULES (from flutter.dev/perf):
- 16ms frame budget for 60fps, 8ms for 120fps devices
- Jank = frame takes > 16ms to build OR raster
- Never: async calls, setState, heavy computation, or network requests in build()
- ListView.builder mandatory for lists > 20 items (ListView renders all children)
- Image.network: always set width/height/cacheWidth to avoid layout thrashing
- Avoid Opacity widget for animations — use AnimatedOpacity or FadeTransition
- Use const constructors everywhere possible — Flutter skips rebuild entirely
- RepaintBoundary around animations, maps, or any expensive independently-animated widget

━━━ FLUTTER VERSION HISTORY (last 5 major versions) ━━━

─── Flutter 3.41 ───────────────────────────
## Flutter 3.41 Changes

### [3.41.7](https://github.com/flutter/flutter/releases/tag/3.41.7)
- [flutter/184376](https://github.com/flutter/flutter/issues/184376) When building an iOS or macOS app, the build may fail due to git multi-pack-index error.
- [flutter/184254](https://github.com/flutter/flutter/issues/184254) When debugging on physical iOS devices and Xcode 26.4+, app often crashes.
- [flutter/184689](https://github.com/flutter/flutter/issues/184689) When using an ffi Windows package, don't require a plugin class.

### [3.41.6](https://github.com/flutter/flutter/releases/tag/3.41.6)
- [flutter/184025](https://github.com/flutter/flutter/pull/184025) Include a fix from Skia that ensures that the correct atlas for the glyph mask format is used consistently.
- [flutter/182708](https://github.com/flutter/flutter/issues/182708) Visual issues with circles appearing jagged. Especially on thin stroked circles and circles with small radii.
- [flutter/183887](https://github.com/flutter/flutter/issues/183887) During SCREEN_OFF event a deadlock preventing new frames causing an ANR can occur on android devices running the Android 16 March Security update.

### [3.41.5](https://github.com/flutter/flutter/releases/tag/3.41.5)
- [flutter/182708](https://github.com/flutter/flutter/issues/182708) When using Impeller on any platform, bur artifacts in circles rendering at 45 degree angles.

### [3.41.4](https://github.com/flutter/flutter/releases/tag/3.41.4)
- [flutter/182748](https://g
  ...(more fixes not shown)

─── Flutter 3.38 ───────────────────────────
## Flutter 3.38 Changes

### [3.38.10](https://github.com/flutter/flutter/releases/tag/3.38.10)

- [flutter/181607](https://github.com/flutter/flutter/pull/181607) When using an ffi plugin on macOS, generated frameworks have the wrong structure.

### [3.38.9](https://github.com/flutter/flutter/releases/tag/3.38.9)

- [flutter/181568](https://github.com/flutter/flutter/pull/181568) Update Dart to 3.10.8.

### [3.38.8](https://github.com/flutter/flutter/releases/tag/3.38.8)

- [flutter/178151](https://github.com/flutter/flutter/issues/178151) - `flutter run -d chrome` may crash with a `DartDevelopmentServiceException` when the application shuts down during the startup sequence.

### [3.38.7](https://github.com/flutter/flutter/releases/tag/3.38.7)

- [flutter/179857](https://github.com/flutter/flutter/issues/179857) - `flutter run -d all` crashes if multiple devices are available.

### [3.38.6](https://github.com/flutter/flutter/releases/tag/3.38.6)

- [flutter/179139](https://github.com/flutter/flutter/issues/179139) - `flutter widget-preview start` creates new cached build artifacts on each run, resulting in increasing disk usage after each run.
- [flutter/178896](https://github.com/flutter/flutter/issues/178896) - Apps crash during launch on Windows when run from paths containing non-ASCII characters.
- [flutter/176943](https://github.com/flutter/flutter/issues/176943) - Configuration changes to run tests on macOS 15 or 15.7.2 for Flutter's CI.
- [flutter/179914](https://gith
  ...(more fixes not shown)

─── Flutter 3.35 ───────────────────────────
## Flutter 3.35 Changes

### [3.35.7](https://github.com/flutter/flutter/releases/tag/3.35.7)

- [flutter/174082](https://github.com/flutter/flutter/issues/174082) Apps, on all platforms, that extend MenuController class see a compile time failure when building.
- [flutter/173770](https://github.com/flutter/flutter/issues/173770) Mitigates a memory leak that occurs on Android, when `Activities` are not kept upon exit and an Activity is exited and re-entered.

### [3.35.6](https://github.com/flutter/flutter/releases/tag/3.35.6)

- [flutter/175669](https://github.com/flutter/flutter/issues/175669) `flutter analyze --suggestions` supports versions up to Java 25, Gradle 9 and AGP 9, Kotlin 2.2.20.
- [flutter/172624](https://github.com/flutter/flutter/issues/172624) Fixes an issue that could result in a corrupt pipeline cache when using the Impeller Vulkan back end.

### [3.35.5](https://github.com/flutter/flutter/releases/tag/3.35.5)

 - [flutter/172105](https://github.com/flutter/flutter/issues/172105) Flutter view no longer hangs after multiple transitions on iOS add-to-app.
 - [flutter/173106](https://github.com/flutter/flutter/issues/173106) Multiple cursors display correctly.

### [3.35.4](https://github.com/flutter/flutter/releases/tag/3.35.4)
- [flutter/173474](https://github.com/flutter/flutter/issues/173474) - On all platforms PlatformDispatchers.instance.engineId no longer returns null after hot restart.
- [flutter/174513](https://github.com/flutter/flutter/issues/17451
  ...(more fixes not shown)

─── Flutter 3.32 ───────────────────────────
## Flutter 3.32 Changes

### [3.32.8](https://github.com/flutter/flutter/releases/tag/3.32.8)

- [flutter/150131](https://github.com/flutter/flutter/issues/150131) iOS users on macOS 15 may see a tool crash if permissions are missing. Can work around by enabling mDNS permissions.
- [flutter/155294](https://github.com/flutter/flutter/issues/155294) [flutter/169506](https://github.com/flutter/flutter/issues/169506) On android Add a new api for requesting a new surface from the embedder that is different from any previously returned.
- [flutter/172602](https://github.com/flutter/flutter/pull/172602)  Do not call hasUnifiedMemory that was introduced in macOS 10.15 on versions before 10.15.
- [flutter/172250](https://github.com/flutter/flutter/issues/172250) `TextInput.hide` call incorrectly clears the text in the active text field on iOS.

### [3.32.7](https://github.com/flutter/flutter/releases/tag/3.32.7)

- [flutter/172121](https://github.com/flutter/flutter/pull/172121) - Fix iOS images replaced with pink fill when coming out of background.

### [3.32.6](https://github.com/flutter/flutter/releases/tag/3.32.6)

- [flutter/171106](https://github.com/flutter/flutter/pull/171106) - When a scroll view contains a `LayoutBuilder` on any platform, prevent null check crash.
- [flutter/171239](https://github.com/flutter/flutter/pull/171239) - When using Impeller + Vulkan and transitioning between activities that use Flutter on Android, prevent a crash.
- [flutter/171737](https://github
  ...(more fixes not shown)

─── Flutter 3.29 ───────────────────────────
## Flutter 3.29 Changes

### [3.29.3](https://github.com/flutter/flutter/releases/tag/3.29.3)
- [flutter/165818](https://github.com/flutter/flutter/pull/165818) - Unset `GIT_DIR` to enable flutter tool calls in githooks.
- [flutter/163421](https://github.com/flutter/flutter/issues/163421) - Impeller,
  Android, Fixes Android Emulator crash when navigating to routes with backdrop
  blurs.
- [flutter/165166](https://github.com/flutter/flutter/pull/165166) - Impeller, All platforms, Text that is scaled over 48x renders incorrectly.
- [flutter/163627](https://github.com/flutter/flutter/pull/163627) - Fix issue where placeholder types in ARB localizations weren't used for type inference, causing a possible type mismatch with the placeholder field defined in the template.
- [flutter/165166](https://github.com/flutter/flutter/pull/165166) - Update CI configurations and tests to use Xcode 16 and iOS 18 simulator.
- [flutter/161466](https://github.com/flutter/flutter/pull/161466) - Hot restart can hang on all platforms if "Pause on Unhandled Exceptions" is enabled by the debugger and a call to `compute` or `Isolate.run` has not completed.

### [3.29.2](https://github.com/flutter/flutter/releases/tag/3.29.2)

- [dart 3.7.2 changelog](https://github.com/dart-lang/sdk/blob/stable/CHANGELOG.md#372)
- [flutter/164958](https://github.com/flutter/flutter/issues/164958) - Impeller, All platforms, Text that is rotated 180 degrees exactly will render as if it is scaled by {-1, 1} instead of {-1
  ...(more fixes not shown)



━━━ FLUTTER TESTING OFFICIAL DOCS ━━━

---
title: Testing Flutter apps
description: >-
  Learn more about the different types of testing and how to write them.
---

The more features your app has, the harder it is to test manually.
Automated tests help ensure that your app performs correctly before
you publish it, while retaining your feature and bug fix velocity.

Automated testing falls into a few categories:

* A [_unit test_](#unit-tests) tests a single function, method, or class.
* A [_widget test_](#widget-tests) (in other UI frameworks referred to
  as _component test_) tests a single widget.
* An [_integration test_](#integration-tests)
  tests a complete app or a large part of an app.

Generally speaking, a well-tested app has many unit and widget tests,
tracked by [code coverage][], plus enough integration tests
to cover all the important use cases. This advice is based on
the fact that there are trade-offs between different kinds of testing,
seen below.

| Tradeoff             | Unit   | Widget | Integration |
|----------------------|--------|--------|-------------|
| **Confidence**       | Low    | Higher | Highest     |
| **Maintenance cost** | Low    | Higher | Highest     |
| **Dependencies**     | Few    | More   | Most        |
| **Execution speed**  | Quick  | Quick  | Slow        |

{:.table .table-striped}

## Unit tests

A _unit test_ tests a single function, method, or class.
The goal of a unit test is to verify the correctness of a
unit of logic under a variety of conditions.
External dependencies of the unit under test are generally
[mocked out](/cookbook/testing/unit/mocking).
Unit tests generally don't read from or write
to disk, render to screen, or receive user actions from
outside the process running the test.
For more information regarding unit tests,
you can view the following recipes
or run `flutter test --help` in your terminal.

:::note
If you're writing unit tests for code that
uses plugins and you want to avoid crashes,
check out [Plugins in Flutter tests][].
If you want to test your Flutter plugin,
check out [Testing plugins][].
:::

[Plugins in Flutter tests]: /testing/plugins-in-tests
[Testing plugins]: /testing/testing-plugins

### Recipes {:.no_toc}

- [Introduction to unit testing](/cookbook/testing/unit/introduction)
- [Mock dependencies using Mockito](/cookbook/testing/unit/mocking)

## Widget tests

A _widget test_ (in other UI frameworks referred to as _component test_)
tests a single widget. The goal of a widget test is to verify that the
widget's UI looks and interacts as expected. Testing a widget involves
multiple classes and requires a test environment that provides the
appropriate widget lifecycle context.

For example, the Widget being tested should be able to receive and
respond to user actions and events, perform layout, and instantiate child
widgets. A widget test is therefore more comprehensive than a unit test.
However, like a unit test, a widget test's environment is replaced with
an implementation much simpler than a full-blo
...(truncated)

━━━ FLUTTER PERFORMANCE OFFICIAL DOCS ━━━

---
title: Performance best practices
shortTitle: Best practices
description: How to ensure that your Flutter app is performant.
---



Generally, Flutter applications are performant by default,
so you only need to avoid common pitfalls to get excellent
performance. These best practice recommendations will help you
write the most performant Flutter app possible.

:::note
If you are writing web apps in Flutter, you might be interested
in a series of articles, written by the Flutter Material team,
after they modified the [Flutter Gallery][] app to make it more
performant on the web:

* [Optimizing performance in Flutter web apps with tree
  shaking and deferred loading][web-perf-1]
* [Improving perceived performance with image placeholders,
  precaching, and disabled navigation transitions][web-perf-2]
* [Building performant Flutter widgets][web-perf-3]
:::

[Flutter Gallery]: {{site.gallery-archive}}
[web-perf-1]: {{site.flutter-blog}}/optimizing-performance-in-flutter-web-apps-with-tree-shaking-and-deferred-loading-535fbe3cd674
[web-perf-2]: {{site.flutter-blog}}/improving-perceived-performance-with-image-placeholders-precaching-and-disabled-navigation-6b3601087a2b
[web-perf-3]: {{site.flutter-blog}}/building-performant-flutter-widgets-3b2558aa08fa

How do you design a Flutter app to most efficiently
render your scenes? In particular, how do you ensure
that the painting code generated by the
framework is as efficient as possible?
Some rendering and layout operations are known
to be slow, but can't always be avoided.
They should be used thoughtfully,
following the guidance below.

## Minimize expensive operations

Some operations are more expensive than others,
meaning that they consume more resources.
Obviously, you want to only use these operations
when necessary. How you design and implement your
app's UI can have a big impact on how efficiently it runs.

### Control build() cost

Here are some things to keep in mind when designing your UI:

* Avoid repetitive and costly work in `build()` methods
  since `build()` can be invoked frequently when
  ancestor widgets rebuild.
* Avoid overly large single widgets with a large `build()` function.
  Split them into different widgets based on encapsulation
  but also on how they change:
  * When `setState()` is called on a `State` object,
    all descendent widgets rebuild. Therefore,
    localize the `setState()` call to the part of
    the subtree whose UI actually needs to change.
    Avoid calling `setState()` high up in the tree
    if the change is contained to a small part of the tree.
  * The traversal to rebuild all descendents stops when the
    same instance of the child widget as the previous
    frame is re-encountered. This technique is heavily
    used inside the framework for optimizing
    animations where the animation doesn't affect the child subtree.
    See the [`TransitionBuilder`][] pattern and
    the [source code for `SlideTransition`][],
    which uses this principle to avoid r
...(truncated)

━━━ FLUTTER LAYOUT CONSTRAINTS ━━━

---
title: Understanding constraints
description: Flutter's model for widget constraints, sizing, positioning, and how they interact.
showToc: false
---





:::note
If you are experiencing specific layout errors,
you might check out [Common Flutter errors][].
:::

[Common Flutter errors]: /testing/common-errors

When someone learning Flutter asks you why some widget
with `width: 100` isn't 100 pixels wide,
the default answer is to tell them to put that widget
inside of a `Center`, right?

**Don't do that.**

If you do, they'll come back again and again,
asking why some `FittedBox` isn't working,
why that `Column` is overflowing, or what
`IntrinsicWidth` is supposed to be doing.

Instead, first tell them that Flutter layout is very different
from HTML layout (which is probably where they're coming from),
and then make them memorize the following rule:


Constraints go down. Sizes go up. Parent sets position.


Flutter layout can't really be understood without knowing
this rule, so Flutter developers should learn it early on.

In more detail:

* A widget gets its own **constraints** from its **parent**.
  A _constraint_ is just a set of 4 doubles:
  a minimum and maximum width, and a minimum and maximum height.
* Then the widget goes through its own list of **children**.
  One by one, the widget tells its children what their
  **constraints** are (which can be different for each child),
  and then asks each child what size it wants to be.
* Then, the widget positions its **children**
  (horizontally in the `x` axis, and vertically in the `y` axis),
  one by one.
* And, finally, the widget tells its parent about its own **size**
  (within the original constraints, of course).

For example, if a composed widget contains a column
with some padding, and wants to lay out its two children
as follows:



The negotiation goes something like this:

**Widget**: "Hey parent, what are my constraints?"

**Parent**: "You must be from `0` to `300` pixels wide,
   and `0` to `85` ta
...(truncated)

━━━ DEVTOOLS — PERFORMANCE PROFILING ━━━

---
title: Use the Performance view
description: Learn how to use the DevTools performance view.
---

:::note
The DevTools performance view works for Flutter mobile and desktop apps.
For web apps, Flutter adds timeline events to the
performance panel of Chrome DevTools instead.
To learn about profiling web apps,
check out [Debugging web performance][].
:::

[Debugging web performance]: /perf/web-performance

The performance page can help you diagnose performance
problems and UI jank in your application.
This page offers timing and performance information
for activity in your application.
It consists of several tools to help you identify
the cause of poor performance in your app:

* Flutter frames chart (Flutter apps only)
* Frame analysis tab (Flutter apps only)
* Timeline events trace viewer (all native Dart applications)
* Advanced debugging tools (Flutter apps only)

:::secondary
**Use a [profile build][] of your application to analyze performance.**
Frame rendering times aren't indicative of release performance
when running in debug mode. Run your app in profile mode,
which still preserves useful debugging information.
:::

[profile build]: /testing/build-modes#profile

The performance view also supports importing and exporting of
data snapshots. For more information,
check out the [Import and export][] section.

## What is a frame in Flutter?

Flutter is designed to render its UI at 60 frames per second
(fps), or 120 fps on devices capable of 120Hz updates.
Each render is called a _frame_.
This means that, approximately every 16ms, the UI updates
to reflect animations or other changes to the UI. A frame
that takes longer than 16ms to render causes jank
(jerky motion) on the display device.

## Flutter frames chart

This chart contains Flutter frame information for your application.
Each bar set in the chart represents a single Flutter frame.
The bars are color-coded to highlight the different portions
of work that occur when rendering a Flutter frame: work from
...(truncated)

━━━ DEVTOOLS — MEMORY & LEAK DETECTION ━━━

---
title: Use the Memory view
description: Learn how to use the DevTools memory view.
---

The memory view provides insights into details
of the application's memory allocation and
tools to detect and debug specific issues.

:::note
This page is up to date for DevTools 2.23.0.
:::

For information on how to locate DevTools screens in different IDEs,
check out the [DevTools overview](/tools/devtools).

To better understand the insights found on this page,
the first section explains how Dart manages memory.
If you already understand Dart's memory management,
you can skip to the [Memory view guide](#memory-view-guide).

## Reasons to use the memory view

Use the memory view for preemptive memory optimization or when
your application experiences one of the following conditions:

* Crashes when it runs out of memory
* Slows down
* Causes the device to slow down or become unresponsive
* Shuts down because it exceeded the memory limit, enforced by operating system
* Exceeds memory usage limit
  * This limit can vary depending on the type of devices your app targets.
* Suspect a memory leak

## Basic memory concepts

Dart objects created using a class constructor
(for example, by using `MyClass()`) live in a
portion of memory called the _heap_. The memory
in the heap is managed by the Dart VM (virtual machine).
The Dart VM allocates memory for the object at the moment of the object creation,
and releases (or deallocates) the memory when the object
is no longer used (see [Dart garbag
...(truncated)

━━━ ANDROID DEPLOYMENT ━━━

---
title: Build and release an Android app
description: How to prepare for and release an Android app to the Play store.
shortTitle: Android
---

To test an app, you can use `flutter run` at the command line,
or the **Run** and **Debug** options in your IDE.

When you're ready to prepare a _release_ version of your app,
for example to [publish to the Google Play Store][play],
this page can help. Before publishing,
you might want to put some finishing touches on your app.
This guide explains how to perform the following tasks:

* [Add a launcher icon](#add-a-launcher-icon)
* [Enable Material Components](#enable-material-components)
* [Sign the app](#sign-the-app)
* [Shrink your code with R8](#shrink-your-code-with-r8)
* [Enable multidex support](#enable-multidex-support)
* [Review the app manifest](#review-the-app-manifest)
* [Review the build configuration](#review-the-gradle-build-configuration)
* [Build the app for release](#build-the-app-for-release)
* [Publish to the Google Play Store](#publish-to-the-google-play-store)
* [Update the app's version number](#update-the-apps-version-number)
* [Android release FAQ](#android-release-faq)

:::note
Throughout this page, `[project]` refers to
the directory that contains your application.
While following these instructions,
substitute `[project]` with your app's directory.
:::

[play]: {{site.android-dev}}/distribute

## Add a launcher icon

When a new Flutter app is created, it has a default launcher icon.
To customize this icon
...(truncated)

━━━ NETWORKING & ASYNC COOKBOOK ━━━

---
title: Fetch data from the internet
description: How to fetch data over the internet using the http package.
---



Fetching data from the internet is necessary for most apps.
Luckily, Dart and Flutter provide tools, such as the
`http` package, for this type of work.

:::note
You should avoid directly using `dart:io` or `dart:html`
to make HTTP requests.
Those libraries are platform-dependent
and tied to a single implementation.
:::

This recipe uses the following steps:

  1. Add the `http` package.
  2. Make a network request using the `http` package.
  3. Convert the response into a custom Dart object.
  4. Fetch and display the data with Flutter.

## 1. Add the `http` package

The [`http`][] package provides the
simplest way to fetch data from the internet.

To add the `http` package as a dependency,
run `flutter pub add`:



Import the http package.






## 2. Make a network request

This recipe covers how to fetch a sample album from the
[JSONPlaceholder][] using the [`http.get()`][] method.




The `http.get()` method returns a `Future` that contains a `Response`.

* [`Future`][] is a core Dart class for working with
  async operations. A Future object represents a potential
  value or error that will be available at some time in the future.
* The `http.Response` class contains the data received from a successful
  http call.

## 3. Convert the response into a custom Dart object

While it's easy to make a network request, working with a raw
`Future` isn't very con
...(truncated)
''';
