// Run this to manually update bundled knowledge files:
//   dart run tool/update_knowledge.dart
//
// The GitHub Actions workflow runs this automatically every week.
// Run it locally whenever you want to pull the latest Flutter changelog.
//
// Behavior on fetch failure: the previous run's content for that section is
// kept (a transient 404 can never erase good knowledge). If any section ends
// up with no content at all, the tool exits non-zero WITHOUT writing
// layer1_content.dart, so neither CI nor a local run can leave a degraded
// file in the tree.
//
// All pure logic lives in tool/src/knowledge_builder.dart (unit-tested in
// test/knowledge_builder_test.dart); this file is only I/O.

import 'dart:io';
import 'package:http/http.dart' as http;

import 'src/knowledge_builder.dart';

const _layer1Out = 'lib/ai/knowledge/layer1_content.dart';
const _layer2Out = 'lib/ai/knowledge/layer2_content.dart';

// Sources we fetch for Layer 1. The flutter/website repo hosts flutter.dev
// content under sites/docs/src/content/ (moved from src/content/ in 2026).
const _sources = {
  'changelog':
      'https://raw.githubusercontent.com/flutter/flutter/master/CHANGELOG.md',
  'testing':
      'https://raw.githubusercontent.com/flutter/website/main/sites/docs/src/content/testing/overview.md',
  'performance':
      'https://raw.githubusercontent.com/flutter/website/main/sites/docs/src/content/perf/best-practices.md',
  'constraints':
      'https://raw.githubusercontent.com/flutter/website/main/sites/docs/src/content/ui/layout/constraints.md',
  'devtools_perf':
      'https://raw.githubusercontent.com/flutter/website/main/sites/docs/src/content/tools/devtools/performance.md',
  'devtools_memory':
      'https://raw.githubusercontent.com/flutter/website/main/sites/docs/src/content/tools/devtools/memory.md',
  'android_deploy':
      'https://raw.githubusercontent.com/flutter/website/main/sites/docs/src/content/deployment/android.md',
  'fetch_data':
      'https://raw.githubusercontent.com/flutter/website/main/sites/docs/src/content/cookbook/networking/fetch-data.md',
};

// Per-section prompt budgets (chars after markdown stripping).
const _sectionBudgets = {
  'testing': 3000,
  'performance': 3000,
  'constraints': 2000,
  'devtools_perf': 2000,
  'devtools_memory': 1500,
  'android_deploy': 1500,
  'fetch_data': 1500,
};

// Layer 2 lives in this repo — no network fetch, no dead URL.
const _layer2Source = 'knowledge/community_patterns.md';

Future<void> main() async {
  print('🔄 Updating Dangi Doctor knowledge files...\n');
  final layer1Missing = await _updateLayer1();
  final layer2Ok = _updateLayer2();

  if (layer1Missing.isNotEmpty) {
    stderr.writeln(
        '\n❌ Sections with no content (fetch failed and no previous data): '
        '${layer1Missing.join(', ')}');
    exitCode = 1;
    return;
  }
  if (!layer2Ok) {
    exitCode = 1;
    return;
  }
  print('\n✅ Done. Run `dart analyze lib/ai/knowledge/` to verify.');
}

Future<List<String>> _updateLayer1() async {
  print('📥 Fetching Flutter official sources...');

  final fresh = <String, String>{};
  for (final entry in _sources.entries) {
    final raw = await _fetch(entry.key, entry.value);
    fresh[entry.key] = entry.key == 'changelog'
        ? (raw.isEmpty ? '' : parseChangelog(raw))
        : (raw.isEmpty ? '' : trimMarkdown(raw, _sectionBudgets[entry.key]!));
  }

  final outFile = File(_layer1Out);
  final previous = outFile.existsSync() ? outFile.readAsStringSync() : null;
  final merged = mergeWithPrevious(fresh: fresh, previousFile: previous);

  for (final key in fresh.keys) {
    if (fresh[key]!.trim().isEmpty && merged[key]!.trim().isNotEmpty) {
      print('  ⚠️  $key: fetch failed — kept previous content');
    }
  }

  // Check-then-write: a run with missing sections must not touch the file,
  // so a failed local run can never leave a degraded layer1_content.dart.
  final generated = renderLayer1FileOrNull(merged);
  if (generated == null) {
    stderr.writeln(
        '  ⛔ Layer 1 NOT written — keeping the previous $_layer1Out untouched.');
    return missingSections(merged);
  }

  outFile.writeAsStringSync(generated);
  print('  ✅ Layer 1 updated → $_layer1Out');

  return const [];
}

bool _updateLayer2() {
  print('📥 Reading community patterns from $_layer2Source...');
  final source = File(_layer2Source);
  if (!source.existsSync()) {
    stderr.writeln('  ❌ $_layer2Source not found');
    return false;
  }
  final content = source.readAsStringSync().trim();
  if (content.isEmpty) {
    stderr.writeln('  ❌ $_layer2Source is empty');
    return false;
  }
  File(_layer2Out).writeAsStringSync(generateDartConst(
    varName: 'kLayer2Content',
    comment:
        '// AUTO-GENERATED by tool/update_knowledge.dart — do not edit manually.\n'
        '// Source: knowledge/community_patterns.md (this repo). Edit that file\n'
        '// and re-run the tool (or let the weekly workflow regenerate this).',
    content: content,
  ));
  print('  ✅ Layer 2 updated → $_layer2Out');
  return true;
}

Future<String> _fetch(String name, String url) async {
  try {
    final res =
        await http.get(Uri.parse(url)).timeout(const Duration(seconds: 15));
    if (res.statusCode == 200) return res.body;
    stderr.writeln('  ⚠️  $name: HTTP ${res.statusCode}');
    return '';
  } catch (e) {
    stderr.writeln('  ⚠️  $name: $e');
    return '';
  }
}
